console.log("Samandar: Hi! What's your name?");
console.log("Sabina: Hi! My name is Sabina. What's yours?");
console.log("Samandar: My name is Samandar. Nice to meet you, Sabina.");
console.log("Sabina: Nice to meet you too, Samandar. How old are you?");
console.log("Samandar: I'm 20 years old. And you?");
console.log("Sabina: I'm also 20 years old. What a coincidence!");
console.log("Samandar: Where do you study?");
console.log("Sabina: I study graphic design at Najot Ta'lim. And you?");
console.log("Samandar: I also study at Najot Ta'lim, but in programming.");
console.log("Sabina: That's interesting! What do you do in your free time?");
console.log("Samandar: I play sports, especially football. What about you?");
console.log("Sabina: I love reading books and drawing.");
console.log("Samandar: I also like football. Which team do you support?");
console.log("Sabina: I like Barcelona. And you?");
console.log("Samandar: I support Real Madrid.");
console.log("Sabina: Interesting, so we're rivals!");
console.log("Samandar: Yes, but that's good, it makes our conversation interesting.");
console.log("Sabina: You're right. What movie did you watch recently?");
console.log("Samandar: I watched 'Inception'. I really liked it. What about you?");
console.log("Sabina: I also watched that movie and really liked it. The direction was amazing.");
console.log("Samandar: Yes, indeed. Nice to meet you, Sabina.");
console.log("Sabina: Nice to meet you too, Samandar. Goodbye!");
console.log("Samandar: Goodbye, Sabina!");